# 认识Numpy中的ndarray
## 构造ndarray对象

In [4]:
# 1. 构造二维的ndarray
import numpy as np

In [ ]:
# 构造 2行4列全是0 的uchar类型的二维数组
z = np.zeros((2,4), np.uint8)  # 构造2行4列的矩阵
type(z)

In [3]:
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [5]:
# 构造一个2行4列全是1的整型矩阵
o = np.ones((2, 4), np.int32)
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
# 初始化一个浮点型矩阵
m = np.array([[4, 12, 3, 1], [10, 12, 14, 29]], np.float32)
m

array([[ 4., 12.,  3.,  1.],
       [10., 12., 14., 29.]], dtype=float32)

In [8]:
# 2.构造三维的ndarray
# 初始化一个2*2*4的32位浮点型数组
m = np.array([
                [[1, 2, 3, 4], [5, 6, 7, 8]],
                [[10, 11, 12, 13], [14, 15, 16, 17]]
            ],np.float32)
m

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12., 13.],
        [14., 15., 16., 17.]]], dtype=float32)

In [9]:
# 3. ndarray中的成员变量
m = np.array([[4, 12, 3, 1], [10, 12, 14, 29]], np.float32)
m.dtype  # 数据类型

dtype('float32')

In [11]:
m.shape  # 数据的尺寸

(2, 4)

## 访问ndarray中的值

In [15]:
# 1. 访问二维ndarray中的值
m = np.array([[4, 12, 3, 1], [10, 12, 14, 29], [67, 23, 534, 2]], np.float32)
# 第1行第3列的值
m[1,3]

29.0

In [16]:
# m中第2行的值
m[2:]

array([[ 67.,  23., 534.,   2.]], dtype=float32)

In [17]:
# m中第3列的值
m[:, 3]

array([ 1., 29.,  2.], dtype=float32)

In [19]:
# 第0行第1列至右下角第2行弟3列矩形区域的所有值
m[0:2, 1:3]

array([[12.,  3.],
       [12., 14.]], dtype=float32)

In [21]:
# 2. 访问三维ndarray中的值
m = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]],
    [[10, 11, 12, 13], [15, 16, 17, 18]],
    [[11, 21, 43, 45], [46, 22, 32, 18]]
], np.float32)
m

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12., 13.],
        [15., 16., 17., 18.]],

       [[11., 21., 43., 45.],
        [46., 22., 32., 18.]]], dtype=float32)

In [22]:
# m中二维数据的第0列
m[:, :, 0]

array([[ 1.,  5.],
       [10., 15.],
       [11., 46.]], dtype=float32)

In [23]:
# m中第0个二维数组
m[0, :, :]

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

# 认识OpenCV中的Mat类

## 初识Mat

构造Mat对象相当于构造了一个矩阵(数组)，需要四个基本要素：行数(高)、列数(宽)、通道数及其数据类型。即：

Mat(int rows, int cols, int type) 或 Mat(Size(int cols, int rows), int type)

## 构造单通道Mat对象

In [11]:
# 2行3列float类型的单通道矩阵
m = np.random.random((2,3))
m

array([[0.4008942 , 0.24051842, 0.97282162],
       [0.6513049 , 0.03882022, 0.35182797]])

In [13]:
# 构造一个2行3列全是0的float类型的单通道矩阵
np.zeros((2,3),dtype=np.float32)

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

## 获得单通道Mat的基本信息

In [16]:
# 3行2列的二维矩阵
m = np.array([[11, 12], [33, 43], [51, 16]],dtype=np.float)
m

array([[11., 12.],
       [33., 43.],
       [51., 16.]])

In [20]:
# 获取矩阵的尺寸3行2列
m.shape

(3, 2)

# ndarray的计算

In [39]:
# ndarray的加法
import numpy as np
src1 = np.array([[23, 123, 90], [100, 250, 0]], np.uint8)
src2 = np.array([[125, 150, 60], [100, 10, 40]], np.uint8)
dst = src1 + src2
dst

array([[148,  17, 150],
       [200,   4,  40]], dtype=uint8)

In [27]:
# 减法运算
dst = src1 - src2
dst

array([[154, 229,  30],
       [  0, 240, 216]], dtype=uint8)

In [31]:
# 点乘运算
dst = src1 * src2.astype(np.float32)
dst

array([[ 2875., 18450.,  5400.],
       [10000.,  2500.,     0.]], dtype=float32)

In [33]:
dst = np.multiply(src1, src2.astype(np.float32))
dst

array([[ 2875., 18450.,  5400.],
       [10000.,  2500.,     0.]], dtype=float32)

In [40]:
# 点除运算
dst = src2 / src1
dst # 出现inf是因为分母为0

C:\Users\Kungs\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[5.43478261, 1.2195122 , 0.66666667],
       [1.        , 0.04      ,        inf]])

In [41]:
# ndarray的乘法
src3 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.uint8)
src4 = np.array([[6, 5], [4, 3], [2, 1]], dtype=np.uint8)
dst = np.dot(src3, src4)
dst

array([[20, 14],
       [56, 41]], dtype=uint8)

In [44]:
# 指数运算
src5 = np.array([[6, 5], [4, 3]], np.uint8)
dst2 = np.exp(src4)
dst2

array([[403.5  , 148.4  ],
       [ 54.6  ,  20.08 ],
       [  7.39 ,   2.719]], dtype=float16)

In [46]:
# 对数计算
dst2 = np.log(src4)
dst2

array([[1.792 , 1.609 ],
       [1.387 , 1.099 ],
       [0.6934, 0.    ]], dtype=float16)

In [47]:
# 幂指数运算
src = np.array([[25, 40], [10, 100]], dtype=np.uint8)
dst1 = np.power(src, 2)
dst1

array([[113,  64],
       [100,  16]], dtype=uint8)

In [50]:
# 将幂指数2改为2.0
dst1 = np.power(src, 2.0)
dst1, dst1.dtype

(array([[  625.,  1600.],
        [  100., 10000.]]), dtype('float64'))

# 灰度图像数字化

In [57]:
import sys
import cv2
import numpy as np

if __name__ == "__main__":
    # 输入图像矩阵，转换为array
    if len(sys.argv) > 1:
        img = cv2.imread(sys.argv[1], cv2.IMREAD_GRAYSCALE)
    else:
        print("Usge: python imgToArray.py imageFile")
    # 显示图像
    cv2.imshow("img", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:356: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [ ]:
# 将RGB彩色图像转换为三维的ndarray
import cv2
import numpy as np
import sys

if __name__ == "__main__":
    if len(sys.argv) > 1:
        image = cv2.imread(sys.argv[1], cv2.IMREAD_COLOR)
    else:
        print("Usge: python RGB.py imageFile")
    # 得到三个颜色通道
    b = image[:, :, 0]
    g = image[:, :, 1]
    r = image[:, :, 2]
    # 显示三个颜色通道
    cv2.imshow("b", b)
    cv2.imshow("g", g)
    cv2.imshow("r", r)
    cv2.waitKey(0)
    cv2.destroyAllWindows()